### ISSUE TITLE
The UnderlineNav component adds some styles by default causing the style to be abnormal

### ISSUE THREAD

**Issue by JeffreyBool** [primer/react#1407]
The UnderlineNav component adds some styles by default resulting in abnormal styles, as follows.

![image](https://user-images.githubusercontent.com/24415888/132238192-d60106f3-c40e-4e2e-be93-24f19ea157cf.png)

As above, he will add some random styles

```css
.lcdyUx {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-pack: justify;
    -webkit-justify-content: space-between;
    -ms-flex-pack: justify;
    justify-content: space-between;
    border-bottom: 1px solid;
}
```
